In [ ]:
!pip -q install feast==0.64.0 pyarrow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 72.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 23.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.2/137.2 kB 15.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 22.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 93.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 81.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 kB 46.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 6.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.4.0 requires tenacity<10,>=9, but you have tenacity 8.5.0 which is incompatible.

In [ ]:
import feast

print("Feast version:", feast.__version__)

Feast version: 0.64.0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving CSE_Employability_Skill_Gap_50000_Realistic.xlsx to CSE_Employability_Skill_Gap_50000_Realistic.xlsx

In [ ]:
import pandas as pd

# Get the uploaded Excel filename
filename = next(iter(uploaded))

# Read Excel file
df = pd.read_excel(filename)

print(df.head())
print(df.shape)

  Student_ID  Age  Gender  Degree   Specialization  Current_Year  Semester  \
0  CSE000001   24  Female  B.Tech          AI & ML             2         3
1  CSE000002   20  Female  B.Tech   Cyber Security             3         5
2  CSE000003   23  Female  B.Tech     Data Science             3         5
3  CSE000004   19   Other  B.Tech  Cloud Computing             3         6
4  CSE000005   23    Male  B.Tech          AI & ML             3         5

   CGPA  Attendance_Percentage  Internal_Marks  ...  LeetCode_Problems_Solved  \
0  9.78                    100              79  ...                         0
1  5.99                     91             100  ...                       604
2  6.82                     95              45  ...                       612
3  8.93                     77              69  ...                       783
4  9.25                     70              69  ...                        97

   HackerRank_Badge_Level  Certifications  Hackathons_Attended  Resume_Score  \
0                    Gold              12                    7            81
1                    Gold               8                    9            55
2                  Silver               7                    6            75
3                  Silver               6                    6            69
4                  Bronze               2                   10            83

   Aptitude_Score  Technical_Interview_Score  HR_Interview_Score  \
0              51                         65                  54
1              67                         35                  35
2              81                         35                  35
3              82                         46                  40
4              96                         59                  52

   Mock_Interview_Score  Skill_Gap_Level
0                    57           Medium
1                    37             High
2                    35           Medium
3                    45             High
4                    57           Medium

[5 rows x 101 columns]
(50000, 101)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
print(df.columns)
print(df.info())
print(df.isnull().sum())

Index(['Student_ID', 'Age', 'Gender', 'Degree', 'Specialization',
       'Current_Year', 'Semester', 'CGPA', 'Attendance_Percentage',
       'Internal_Marks',
       ...
       'LeetCode_Problems_Solved', 'HackerRank_Badge_Level', 'Certifications',
       'Hackathons_Attended', 'Resume_Score', 'Aptitude_Score',
       'Technical_Interview_Score', 'HR_Interview_Score',
       'Mock_Interview_Score', 'Skill_Gap_Level'],
      dtype='object', length=101)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Columns: 101 entries, Student_ID to Skill_Gap_Level
dtypes: float64(1), int64(94), object(6)
memory usage: 38.5+ MB
None
Student_ID                   0
Age                          0
Gender                       0
Degree                       0
Specialization               0
                            ..
Aptitude_Score               0
Technical_Interview_Score    0
HR_Interview_Score           0
Mock_Interview_Score         0
Skill_Gap_Level              0
Length: 101, dtype: int64

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [13]:
print(df["Gender"].value_counts(dropna=False))
print(df["Gender"].unique())

Gender
other     16778
female    16696
male      16526
Name: count, dtype: int64
['female' 'other' 'male']

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [16]:
# ==========================================
# Encode Gender
# ==========================================

df["Gender"] = (
    df["Gender"]
    .astype("string")
    .str.strip()
    .str.lower()
)

df["gender_encoded"] = df["Gender"].map({
    "male": 0,
    "female": 1,
    "other": 2
}).astype("int64")

print(df[["Gender", "gender_encoded"]].head(20))
print("\nGender encoding:")
print(df[["Gender", "gender_encoded"]].drop_duplicates())

    Gender  gender_encoded
0   female               1
1   female               1
2   female               1
3    other               2
4     male               0
5   female               1
6    other               2
7   female               1
8    other               2
9   female               1
10  female               1
11  female               1
12    male               0
13  female               1
14    male               0
15  female               1
16   other               2
17    male               0
18    male               0
19    male               0

Gender encoding:
   Gender  gender_encoded
0  female               1
3   other               2
4    male               0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [17]:
# Clean Gender values
df["Gender"] = df["Gender"].astype("string").str.strip().str.lower()

# Encode Gender
df["gender_encoded"] = df["Gender"].map({
    "male": 0,
    "female": 1
})

# Check for values that could not be encoded
print("Missing encoded Gender values:",
      df["gender_encoded"].isna().sum())

print(df[["Gender", "gender_encoded"]].head(20))

Missing encoded Gender values: 16778
    Gender  gender_encoded
0   female             1.0
1   female             1.0
2   female             1.0
3    other             NaN
4     male             0.0
5   female             1.0
6    other             NaN
7   female             1.0
8    other             NaN
9   female             1.0
10  female             1.0
11  female             1.0
12    male             0.0
13  female             1.0
14    male             0.0
15  female             1.0
16   other             NaN
17    male             0.0
18    male             0.0
19    male             0.0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [18]:
import pandas as pd

# ==========================================
# 1. Entity / Student ID
# ==========================================

df["student_id"] = df["Student_ID"].astype(str)


# ==========================================
# 2. Handle missing numerical values
# ==========================================

numerical_columns = [
    "Age",
    "Current_Year",
    "Semester",
    "CGPA",
    "Attendance_Percentage",
    "Internal_Marks",
    "External_Marks",
    "Mini_Project_Score",
    "Major_Project_Score",
    "Lab_Performance",
    "Assignment_Average",
    "Backlogs",
    "Academic_Consistency",
    "Class_Rank"
]

for col in numerical_columns:
    df[col] = df[col].fillna(df[col].median())


# ==========================================
# 3. Encode Gender
# ==========================================

df["Gender"] = (
    df["Gender"]
    .astype("string")
    .str.strip()
    .str.lower()
)

df["gender_encoded"] = df["Gender"].map({
    "male": 0,
    "female": 1,
    "other": 2
}).astype("int64")


# ==========================================
# 4. Derived Feature 1
# Academic Performance Score
# ==========================================

df["academic_score"] = (
    df["CGPA"] +
    df["Attendance_Percentage"] / 10 +
    df["Internal_Marks"] / 10 +
    df["External_Marks"] / 10
) / 4


# ==========================================
# 5. Derived Feature 2
# Project Performance Score
# ==========================================

df["project_score"] = (
    df["Mini_Project_Score"] +
    df["Major_Project_Score"] +
    df["Lab_Performance"]
) / 3


# ==========================================
# 6. Derived Feature 3
# Technical Skill Score
# ==========================================

technical_features = [
    "C_Programming",
    "C++_Programming",
    "Java",
    "Python",
    "JavaScript",
    "SQL",
    "HTML_CSS",
    "ReactJS",
    "NodeJS",
    "Programming_Logic",
    "Arrays",
    "Linked_Lists",
    "Stacks_Queues",
    "Trees",
    "Graphs",
    "Dynamic_Programming",
    "Searching_Sorting",
    "Competitive_Coding",
    "Machine_Learning",
    "Data_Preprocessing",
    "Feature_Engineering",
    "Model_Evaluation"
]

df["technical_skill_score"] = df[technical_features].mean(axis=1)


# ==========================================
# 7. Derived Feature 4
# Soft Skill Score
# ==========================================

soft_skill_features = [
    "Communication",
    "Teamwork",
    "Leadership",
    "Problem_Solving",
    "Critical_Thinking",
    "Time_Management",
    "Adaptability",
    "Creativity",
    "Presentation_Skills",
    "English_Proficiency"
]

df["soft_skill_score"] = df[soft_skill_features].mean(axis=1)


# ==========================================
# 8. Derived Feature 5
# Industry Readiness Score
# ==========================================

df["industry_readiness_score"] = (
    df["Internship_Count"] +
    df["Projects_Completed"] +
    df["Open_Source_Contributions"] +
    df["Hackathons_Attended"]
)


# ==========================================
# 9. Rename / Cast important features
# ==========================================

df["age"] = df["Age"].astype("float32")
df["cgpa"] = df["CGPA"].astype("float32")
df["attendance"] = df["Attendance_Percentage"].astype("float32")
df["backlogs"] = df["Backlogs"].astype("int64")
df["internships"] = df["Internship_Count"].astype("int64")
df["projects"] = df["Projects_Completed"].astype("int64")


# ==========================================
# 10. Target
# ==========================================

df["skill_gap_level"] = df["Skill_Gap_Level"]


# ==========================================
# 11. Check result
# ==========================================

print(df.head())
print("\nDataset shape:", df.shape)
print("\nTarget distribution:")
print(df["skill_gap_level"].value_counts(dropna=False))

  Student_ID  Age  Gender  Degree   Specialization  Current_Year  Semester  \
0  CSE000001   24  female  B.Tech          AI & ML             2         3
1  CSE000002   20  female  B.Tech   Cyber Security             3         5
2  CSE000003   23  female  B.Tech     Data Science             3         5
3  CSE000004   19   other  B.Tech  Cloud Computing             3         6
4  CSE000005   23    male  B.Tech          AI & ML             3         5

   CGPA  Attendance_Percentage  Internal_Marks  ...  technical_skill_score  \
0  9.78                    100              79  ...               7.636364
1  5.99                     91             100  ...               2.500000
2  6.82                     95              45  ...               1.863636
3  8.93                     77              69  ...               5.590909
4  9.25                     70              69  ...               6.454545

   soft_skill_score  industry_readiness_score   age  cgpa  attendance  \
0               6.3                        29  24.0  9.78       100.0
1               1.5                        26  20.0  5.99        91.0
2               2.7                        21  23.0  6.82        95.0
3               5.5                        17  19.0  8.93        77.0
4               6.2                        18  23.0  9.25        70.0

   backlogs  internships  projects  skill_gap_level
0         0            3         4           Medium
1         4            0         8             High
2         2            2         6           Medium
3         4            2         8             High
4         0            3         4           Medium

[5 rows x 115 columns]

Dataset shape: (50000, 115)

Target distribution:
skill_gap_level
High      37154
Medium    12186
Low         660
Name: count, dtype: int64

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [19]:
df[
    [
        "student_id",
        "gender_encoded",
        "age",
        "cgpa",
        "attendance",
        "academic_score",
        "project_score",
        "technical_skill_score",
        "soft_skill_score",
        "industry_readiness_score",
        "skill_gap_level"
    ]
].head()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,student_id,gender_encoded,age,cgpa,attendance,academic_score,project_score,technical_skill_score,soft_skill_score,industry_readiness_score,skill_gap_level
0,CSE000001,1,24.0,9.78,100.0,8.0200,58.666667,7.636364,6.3,29,Medium
1,CSE000002,1,20.0,5.99,91.0,7.8725,89.666667,2.500000,1.5,26,High
2,CSE000003,1,23.0,6.82,95.0,7.3550,93.666667,1.863636,2.7,21,Medium
3,CSE000004,2,19.0,8.93,77.0,8.1325,69.666667,5.590909,5.5,17,High
4,CSE000005,0,23.0,9.25,70.0,7.7125,88.000000,6.454545,6.2,18,Medium

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [20]:
base_time = pd.Timestamp(
    "2025-01-01",
    tz="UTC"
)

df["event_timestamp"] = (
    base_time +
    pd.to_timedelta(
        df["Student_ID"].str.extract(r"(\d+)")[0].astype(int),
        unit="s"
    )
)

df["created_timestamp"] = (
    df["event_timestamp"] +
    pd.Timedelta(seconds=1)
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [21]:
print(
    df[
        [
            "student_id",
            "event_timestamp",
            "created_timestamp"
        ]
    ].head()
)

  student_id           event_timestamp         created_timestamp
0  CSE000001 2025-01-01 00:00:01+00:00 2025-01-01 00:00:02+00:00
1  CSE000002 2025-01-01 00:00:02+00:00 2025-01-01 00:00:03+00:00
2  CSE000003 2025-01-01 00:00:03+00:00 2025-01-01 00:00:04+00:00
3  CSE000004 2025-01-01 00:00:04+00:00 2025-01-01 00:00:05+00:00
4  CSE000005 2025-01-01 00:00:05+00:00 2025-01-01 00:00:06+00:00

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [22]:
feature_df = df[
    [
        "student_id",
        "event_timestamp",
        "created_timestamp",
        "gender_encoded",
        "age",
        "cgpa",
        "attendance",
        "academic_score",
        "project_score",
        "technical_skill_score",
        "soft_skill_score",
        "industry_readiness_score",
        "internships",
        "projects"
    ]
].copy()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [23]:
label_df = df[
    [
        "student_id",
        "event_timestamp",
        "skill_gap_level"
    ]
].copy()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [24]:
print(label_df.head())
print(label_df.shape)

  student_id           event_timestamp skill_gap_level
0  CSE000001 2025-01-01 00:00:01+00:00          Medium
1  CSE000002 2025-01-01 00:00:02+00:00            High
2  CSE000003 2025-01-01 00:00:03+00:00          Medium
3  CSE000004 2025-01-01 00:00:04+00:00            High
4  CSE000005 2025-01-01 00:00:05+00:00          Medium
(50000, 3)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [25]:
print("Feature data:")
display(feature_df.head())

print("Labels:")
display(label_df.head())

Feature data:

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,student_id,event_timestamp,created_timestamp,gender_encoded,age,cgpa,attendance,academic_score,project_score,technical_skill_score,soft_skill_score,industry_readiness_score,internships,projects
0,CSE000001,2025-01-01 00:00:01+00:00,2025-01-01 00:00:02+00:00,1,24.0,9.78,100.0,8.0200,58.666667,7.636364,6.3,29,3,4
1,CSE000002,2025-01-01 00:00:02+00:00,2025-01-01 00:00:03+00:00,1,20.0,5.99,91.0,7.8725,89.666667,2.500000,1.5,26,0,8
2,CSE000003,2025-01-01 00:00:03+00:00,2025-01-01 00:00:04+00:00,1,23.0,6.82,95.0,7.3550,93.666667,1.863636,2.7,21,2,6
3,CSE000004,2025-01-01 00:00:04+00:00,2025-01-01 00:00:05+00:00,2,19.0,8.93,77.0,8.1325,69.666667,5.590909,5.5,17,2,8
4,CSE000005,2025-01-01 00:00:05+00:00,2025-01-01 00:00:06+00:00,0,23.0,9.25,70.0,7.7125,88.000000,6.454545,6.2,18,3,4

Labels:

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

  student_id           event_timestamp skill_gap_level
0  CSE000001 2025-01-01 00:00:01+00:00          Medium
1  CSE000002 2025-01-01 00:00:02+00:00            High
2  CSE000003 2025-01-01 00:00:03+00:00          Medium
3  CSE000004 2025-01-01 00:00:04+00:00            High
4  CSE000005 2025-01-01 00:00:05+00:00          Medium

In [26]:
import os

repo_path = "/content/cse_employability_feast"

os.makedirs(
    f"{repo_path}/data",
    exist_ok=True
)

In [27]:
import os

repo_path = "/content/cse_employability_feast"

os.makedirs(
    f"{repo_path}/data",
    exist_ok=True
)

In [28]:
feature_df.to_parquet(
    f"{repo_path}/data/cse_employability_features.parquet",
    index=False
)

In [29]:
feature_store_yaml = """
project: cse_employability_project

registry: data/registry.db

provider: local

offline_store:
  type: file

online_store:
  type: sqlite
  path: data/online_store.db
"""

with open(
    f"{repo_path}/feature_store.yaml",
    "w"
) as f:
    f.write(feature_store_yaml)

In [30]:
feature_definition = '''
from datetime import timedelta

from feast import (
    Entity,
    FeatureView,
    FeatureService,
    Field,
    FileSource
)

from feast.types import (
    Float32,
    Int64
)

# -----------------------------
# ENTITY
# -----------------------------

student = Entity(
    name="student",
    join_keys=["student_id"],
    description="CSE student for employability skill gap analysis"
)

# -----------------------------
# DATA SOURCE
# -----------------------------

cse_employability_source = FileSource(
    name="cse_employability_source",
    path="data/cse_employability_features.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp"
)

# -----------------------------
# FEATURE VIEW
# -----------------------------

cse_employability_feature_view = FeatureView(
    name="cse_employability_features",
    entities=[student],

    ttl=timedelta(days=50000),

    schema=[
        Field(name="gender_encoded", dtype=Int64),
        Field(name="age", dtype=Float32),
        Field(name="cgpa", dtype=Float32),
        Field(name="attendance", dtype=Float32),
        Field(name="academic_score", dtype=Float32),
        Field(name="project_score", dtype=Float32),
        Field(name="technical_skill_score", dtype=Float32),
        Field(name="soft_skill_score", dtype=Float32),
        Field(name="industry_readiness_score", dtype=Float32),
        Field(name="internships", dtype=Int64),
        Field(name="projects", dtype=Int64),
    ],

    source=cse_employability_source,

    online=True
)

# -----------------------------
# FEATURE SERVICE
# -----------------------------

cse_employability_feature_service = FeatureService(
    name="cse_employability_service",
    features=[
        cse_employability_feature_view
    ]
)
'''

with open(
    f"{repo_path}/features.py",
    "w"
) as f:
    f.write(feature_definition)

In [31]:
!find /content/cse_employability_feast -maxdepth 2 -type f

/content/cse_employability_feast/data/cse_employability_features.parquet
/content/cse_employability_feast/feature_store.yaml
/content/cse_employability_feast/features.py

In [32]:
%cd /content/cse_employability_feast

/content/cse_employability_feast

In [33]:
!feast apply

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/content/cse_employability_feast/features.py:21: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity 'student'.
  student = Entity(
No project found in the repository. Using project name cse_employability_project defined in feature_store.yaml
Applying changes for project cse_employability_project
Created project cse_employability_project
Created entity student
Created feature view cse_employability_features
Created feature service cse_employability_service

Created sqlite table cse_employability_project_cse_employability_features

In [34]:
!feast entities list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME     DESCRIPTION                                       TYPE
student  CSE student for employability skill gap analysis  ValueType.UNKNOWN

In [35]:
!feast feature-views list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME                        ENTITIES     TYPE         ENABLED    STATE
cse_employability_features  {'student'}  FeatureView  Yes        STATE_UNSPECIFIED

In [36]:
from feast import FeatureStore

store = FeatureStore(
    repo_path="/content/cse_employability_feast"
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [37]:
feature_service = store.get_feature_service(
    "cse_employability_service"
)

In [38]:
entity_df = label_df.copy()

display(entity_df.head())

  student_id           event_timestamp skill_gap_level
0  CSE000001 2025-01-01 00:00:01+00:00          Medium
1  CSE000002 2025-01-01 00:00:02+00:00            High
2  CSE000003 2025-01-01 00:00:03+00:00          Medium
3  CSE000004 2025-01-01 00:00:04+00:00            High
4  CSE000005 2025-01-01 00:00:05+00:00          Medium

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [39]:
training_data = store.get_historical_features(
    entity_df=entity_df,
    features=feature_service
).to_df()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [40]:
display(training_data.head())

,student_id,event_timestamp,skill_gap_level,gender_encoded,age,cgpa,attendance,academic_score,project_score,technical_skill_score,soft_skill_score,industry_readiness_score,internships,projects
0,CSE000001,2025-01-01 00:00:01+00:00,Medium,1,24.0,9.78,100.0,8.0200,58.666667,7.636364,6.3,29,3,4
1,CSE000002,2025-01-01 00:00:02+00:00,High,1,20.0,5.99,91.0,7.8725,89.666667,2.500000,1.5,26,0,8
2,CSE000003,2025-01-01 00:00:03+00:00,Medium,1,23.0,6.82,95.0,7.3550,93.666667,1.863636,2.7,21,2,6
3,CSE000004,2025-01-01 00:00:04+00:00,High,2,19.0,8.93,77.0,8.1325,69.666667,5.590909,5.5,17,2,8
4,CSE000005,2025-01-01 00:00:05+00:00,Medium,0,23.0,9.25,70.0,7.7125,88.000000,6.454545,6.2,18,3,4

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [41]:
feature_columns = [
    "gender_encoded",
    "age",
    "cgpa",
    "attendance",
    "academic_score",
    "project_score",
    "technical_skill_score",
    "soft_skill_score",
    "industry_readiness_score",
    "internships",
    "projects"
]

In [43]:
X = training_data[feature_columns]

y = training_data["skill_gap_level"]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

print("\nTraining target distribution:")
print(y_train.value_counts())

print("\nTesting target distribution:")
print(y_test.value_counts())

Training features: (40000, 11)
Testing features: (10000, 11)

Training target distribution:
skill_gap_level
High      29723
Medium     9749
Low         528
Name: count, dtype: int64

Testing target distribution:
skill_gap_level
High      7431
Medium    2437
Low        132
Name: count, dtype: int64

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [45]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

model.fit(
    X_train,
    y_train
)

print("Model training completed successfully.")

Model training completed successfully.

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [46]:
predictions = model.predict(X_test)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [47]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    y_test,
    predictions
)

print(
    "Accuracy:",
    round(accuracy * 100, 2),
    "%"
)

Accuracy: 82.25 %

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [48]:
%cd /content/cse_employability_feast

/content/cse_employability_feast

In [49]:
!feast materialize \
    2025-01-01T00:00:00 \
    2025-01-02T00:00:00

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
Materializing 1 feature views from 2025-01-01 00:00:00+00:00 to 2025-01-02 00:00:00+00:00 into the sqlite online store.

cse_employability_features:

In [52]:
online_features = store.get_online_features(
    features=feature_service,
    entity_rows=[
        {
            "student_id": "CSE000002"
        }
    ]
).to_dict()

In [53]:
print(online_features)

{'student_id': ['CSE000002'], 'age': [20.0], 'project_score': [89.66666412353516], 'soft_skill_score': [1.5], 'industry_readiness_score': [26.0], 'academic_score': [7.872499942779541], 'internships': [0], 'cgpa': [5.989999771118164], 'attendance': [91.0], 'technical_skill_score': [2.5], 'gender_encoded': [1], 'projects': [8]}

In [54]:
online_df = pd.DataFrame(
    online_features
)

display(online_df)

,student_id,age,project_score,soft_skill_score,industry_readiness_score,academic_score,internships,cgpa,attendance,technical_skill_score,gender_encoded,projects
0,CSE000002,20.0,89.666664,1.5,26.0,7.8725,0,5.99,91.0,2.5,1,8

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [55]:
final_model = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

final_model.fit(X, y)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

DecisionTreeClassifier(max_depth=4, random_state=42)

In [56]:
X_online = online_df[
    feature_columns
]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [57]:
prediction = final_model.predict(
    X_online
)

print(
    "Predicted survival:",
    prediction[0]
)

Predicted survival: High

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [58]:
student_ids = df["Student_ID"].head(4).tolist()

online_features = store.get_online_features(
    features=feature_service,
    entity_rows=[
        {"student_id": student_id}
        for student_id in student_ids
    ]
).to_dict()

online_df = pd.DataFrame(
    online_features
)

display(online_df)

,student_id,age,project_score,soft_skill_score,industry_readiness_score,academic_score,internships,cgpa,attendance,technical_skill_score,gender_encoded,projects
0,CSE000001,24.0,58.666668,6.3,29.0,8.0200,3,9.78,100.0,7.636364,1,4
1,CSE000002,20.0,89.666664,1.5,26.0,7.8725,0,5.99,91.0,2.500000,1,8
2,CSE000003,23.0,93.666664,2.7,21.0,7.3550,2,6.82,95.0,1.863636,1,6
3,CSE000004,19.0,69.666664,5.5,17.0,8.1325,2,8.93,77.0,5.590909,2,8

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [60]:
online_df["predicted_skill_gap"] = (
    model.predict(
        online_df[feature_columns]
    )
)

display(
    online_df[
        [
            "student_id",
            "predicted_skill_gap"
        ]
    ]
)

  student_id predicted_skill_gap
0  CSE000001              Medium
1  CSE000002                High
2  CSE000003                High
3  CSE000004                High

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)